<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BusinessPortal.Domain\BusinessPortal.Domain.csproj" />
    <ProjectReference Include="..\..\src\BusinessPortal.Application\BusinessPortal.Application.csproj" />
    <ProjectReference Include="..\..\src\BusinessPortal.Infrastructure\BusinessPortal.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BusinessPortal.Web\BusinessPortal.Web.csproj" />
  </ItemGroup>

</Project>
